const CHATS_ACTION_TYPES = {

  GET_CHAT_PREVIEW: 'GET_CHAT_PREVIEW',
  GET_CHAT_PREVIEW_REQUEST: 'GET_CHAT_PREVIEW_REQUEST',
  GET_CHAT_PREVIEW_SUCCESS: 'GET_CHAT_PREVIEW_SUCCESS',
  GET_CHAT_PREVIEW_FAILED: 'GET_CHAT_PREVIEW_FAILED',

  POST_MESSAGE: 'POST_MESSAGE',
  POST_MESSAGE_REQUEST: 'POST_MESSAGE_REQUEST',
  POST_MESSAGE_SUCCESS: 'POST_MESSAGE_SUCCESS',
  POST_MESSAGE_FAILED: 'POST_MESSAGE_FAILED',

  CREATE_CATALOG: 'CREATE_CATALOG',
  CREATE_CATALOG_SUCCESS: 'CREATE_CATALOG_SUCCESS',
  CREATE_CATALOG_FAILED: 'CREATE_CATALOG_FAILED',

  DELETE_CATALOG: 'DELETE_CATALOG',
  DELETE_CATALOG_SUCCESS: 'DELETE_CATALOG_SUCCESS',
  DELETE_CATALOG_FAILED: 'DELETE_CATALOG_FAILED',

  ADD_CHAT_TO_CATALOG: 'ADD_CHAT_TO_CATALOG',
  ADD_CHAT_TO_CATALOG_SUCCESS: 'ADD_CHAT_TO_CATALOG_SUCCESS',
  ADD_CHAT_TO_CATALOG_FAILED: 'ADD_CHAT_TO_CATALOG_FAILED',

  REMOVE_CHAT_FROM_CATALOG: 'REMOVE_CHAT_FROM_CATALOG',
  REMOVE_CHAT_FROM_CATALOG_SUCCESS: 'REMOVE_CHAT_FROM_CATALOG_SUCCESS',
  REMOVE_CHAT_FROM_CATALOG_FAILED: 'REMOVE_CHAT_FROM_CATALOG_FAILED',

  SET_CHAT_FAVORITE: 'SET_CHAT_FAVORITE',
  SET_CHAT_FAVORITE_SUCCESS: 'SET_CHAT_FAVORITE_SUCCESS',
  SET_CHAT_FAVORITE_FAILED: 'SET_CHAT_FAVORITE_FAILED',

  SET_CHAT_BLOCKED: 'SET_CHAT_BLOCKED',
  SET_CHAT_BLOCKED_SUCCESS: 'SET_CHAT_BLOCKED_SUCCESS',
  SET_CHAT_BLOCKED_FAILED: 'SET_CHAT_BLOCKED_FAILED',

  GET_CATALOG_LIST: 'GET_CATALOG_LIST',
  GET_CATALOG_LIST_SUCCESS: 'GET_CATALOG_LIST_SUCCESS',
  GET_CATALOG_LIST_FAILED: 'GET_CATALOG_LIST_FAILED',

  CHANGE_CATALOG_NAME: 'CHANGE_CATALOG_NAME',
  CHANGE_CATALOG_NAME_SUCCESS: 'CHANGE_CATALOG_NAME_SUCCESS',
  CHANGE_CATALOG_NAME_FAILED: 'CHANGE_CATALOG_NAME_FAILED',

  GET_DIALOG_MESSAGES: 'GET_DIALOG_MESSAGES',
  GET_DIALOG_MESSAGES_SUCCESS: 'GET_DIALOG_MESSAGES_SUCCESS',
  GET_DIALOG_MESSAGES_FAILED: 'GET_DIALOG_MESSAGES_FAILED',

  //NO SAGA ACTIONS
  CLEAR_MESSAGE_LIST: 'CLEAR_MESSAGE_LIST',
  CHANGE_CHAT_SHOW: 'CHANGE_CHAT_SHOW',
  BACK_TO_DIALOG_LIST: 'BACK_TO_DIALOG_LIST',
  CHANGE_RENAME_CATALOG_MODE: 'CHANGE_RENAME_CATALOG_MODE',
  SET_CHAT_PREVIEW_MODE: 'SET_CHAT_PREVIEW_MODE',
  GO_TO_EXPANDED_DIALOG: 'GO_TO_EXPANDED_DIALOG',
  CHANGE_SHOW_MODE_CATALOG: 'CHANGE_SHOW_MODE_CATALOG',
  CHANGE_TYPE_ADDING_CHAT_IN_CATALOG: 'CHANGE_TYPE_ADDING_CHAT_IN_CATALOG',
  CHANGE_SHOW_ADD_CHAT_TO_CATALOG: 'CHANGE_SHOW_ADD_CHAT_TO_CATALOG',
};

export default CHATS_ACTION_TYPES;