const CONTEST_ACTION_TYPES = {
  GET_CONTESTS: 'GET_CONTEST',
  GET_CONTESTS_REQUEST: 'GET_CONTESTS_REQUEST',
  GET_CONTESTS_SUCCESS: 'GET_CONTESTS_SUCCESS',
  GET_CONTESTS_FAILED: 'GET_CONTESTS_ERROR',

  SET_NEW_CUSTOMER_FILTER: 'SET_NEW_CUSTOMER_FILTER',
};

export default CONTEST_ACTION_TYPES;