const CONTEST_ACTION_TYPES = {
  GET_CONTESTS: 'GET_CONTEST',
  GET_ACTIVE_CONTESTS: 'GET_ACTIVE_CONTESTS',
  GET_CONTESTS_REQUEST: 'GET_CONTESTS_REQUEST',
  GET_CONTESTS_SUCCESS: 'GET_CONTESTS_SUCCESS',
  GET_CONTESTS_FAILED: 'GET_CONTESTS_ERROR',

  GET_INDUSTRY_FOR_CONTEST: 'GET_INDUSTRY_FOR_CONTEST',
  GET_INDUSTRY_FOR_CONTEST_REQUEST: 'GET_INDUSTRY_FOR_CONTEST_REQUEST',
  GET_INDUSTRY_FOR_CONTEST_SUCCESS: 'GET_INDUSTRY_FOR_CONTEST_SUCCESS',
  GET_INDUSTRY_FOR_CONTEST_FAILED: 'GET_INDUSTRY_FOR_CONTEST_FAILED',

  SET_NEW_CUSTOMER_FILTER: 'SET_NEW_CUSTOMER_FILTER',
  SET_NEW_CREATOR_FILTER: 'SET_NEW_CREATOR_FILTER',

  SAVE_CREATING_CONTESTS_IN_STORE: 'SAVE_CREATING_CONTESTS_IN_STORE',
  CLEAR_CREATING_CONTESTS_FROM_STORE: 'CLEAR_CREATING_CONTESTS_FROM_STORE',
};

export default CONTEST_ACTION_TYPES;