const OFFER_ACTION_TYPES = {
  GET_OFFERS_FOR_CONTEST: 'GET_OFFERS_FOR_CONTEST',
  GET_OFFERS_FOR_CONTEST_REQUEST: 'GET_OFFERS_FOR_CONTEST_REQUEST',
  GET_OFFERS_FOR_CONTEST_SUCCESS: 'GET_OFFERS_FOR_CONTEST_SUCCESS',
  GET_OFFERS_FOR_CONTEST_FAILED: 'GET_OFFERS_FOR_CONTEST_FAILED',

  ADD_NEW_OFFER: 'ADD_NEW_OFFER',
  ADD_NEW_OFFER_REQUEST: 'ADD_NEW_OFFER_REQUEST',
  ADD_NEW_OFFER_SUCCESS: 'ADD_NEW_OFFER_SUCCESS',
  ADD_NEW_OFFER_FAILED: 'ADD_NEW_OFFER_FAILED',

  SET_OFFER_STATUS: 'SET_OFFER_STATUS',
  SET_OFFER_STATUS_REQUEST: 'SET_OFFER_STATUS_REQUEST',
  SET_OFFER_STATUS_SUCCESS: 'SET_OFFER_STATUS_SUCCESS',
  SET_OFFER_STATUS_FAILED: 'SET_OFFER_STATUS_FAILED',

  CHANGE_OFFER_MARK: 'CHANGE_OFFER_MARK',
  CHANGE_OFFER_MARK_SUCCESS: 'CHANGE_OFFER_MARK_SUCCESS',
  CHANGE_OFFER_MARK_FAILED: 'CHANGE_OFFER_MARK_FAILED',
  CLEAR_MARK_ERROR : 'CLEAR_MARK_ERROR',
};

export default OFFER_ACTION_TYPES;