const OFFER_ACTION_TYPES = {
  GET_OFFERS_FOR_CONTEST: 'GET_OFFERS_FOR_CONTEST',
  GET_OFFERS_FOR_CONTEST_REQUEST: 'GET_OFFERS_FOR_CONTEST_REQUEST',
  GET_OFFERS_FOR_CONTEST_SUCCESS: 'GET_OFFERS_FOR_CONTEST_SUCCESS',
  GET_OFFERS_FOR_CONTEST_FAILED: 'GET_OFFERS_FOR_CONTEST_FAILED',
};

export default OFFER_ACTION_TYPES;