const PAYMENT_ACTION_TYPES = {
  PAYMENT: 'PAYMENT',
  CASHOUT: 'CASHOUT',
  PAYMENT_REQUEST: 'PAYMENT_REQUEST',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_ERROR',
};

export default PAYMENT_ACTION_TYPES;