const PAYMENT_ACTION_TYPES = {
  PAYMENT: 'PAYMENT',
  CASHOUT: 'CASHOUT',
  PAYMENT_REQUEST: 'PAYMENT_REQUEST',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  CHANGE_FOCUS_ON_CARD: 'CHANGE_FOCUS_ON_CARD',
  CLEAR_PAYMENT_STORE: 'CLEAR_PAYMENT_STORE',

};

export default PAYMENT_ACTION_TYPES;