const SINGLE_CONTEST_ACTION_TYPES = {

  GET_DESCRIPTION_FOR_CONTEST: 'GET_DESCRIPTION_FOR_CONTEST',
  GET_DESCRIPTION_FOR_CONTEST_REQUEST: 'GET_DESCRIPTION_FOR_CONTEST_REQUEST',
  GET_DESCRIPTION_FOR_CONTEST_SUCCESS: 'GET_DESCRIPTION_FOR_CONTEST_SUCCESS',
  GET_DESCRIPTION_FOR_CONTEST_FAILED: 'GET_DESCRIPTION_FOR_CONTEST_FAILED',

  SELECT_BUNDLE: 'SELECT_BUNDLE',
};

export default SINGLE_CONTEST_ACTION_TYPES;