const SINGLE_CONTEST_ACTION_TYPES = {

  SELECT_BUNDLE: 'SELECT_BUNDLE',
  CHANGE_CONTEST_VIEW_MODE: 'CHANGE_CONTEST_VIEW_MODE',
  CHANGE_EDIT_CONTEST: 'CHANGE_EDIT_CONTEST',
  CHANGE_SHOW_IMAGE: 'CHANGE_SHOW_IMAGE',
  CHANGE_SHOW_MODAL: 'CHANGE_SHOW_MODAL',

  GET_DESCRIPTION_FOR_CONTEST: 'GET_DESCRIPTION_FOR_CONTEST',
  GET_DESCRIPTION_FOR_CONTEST_REQUEST: 'GET_DESCRIPTION_FOR_CONTEST_REQUEST',
  GET_DESCRIPTION_FOR_CONTEST_SUCCESS: 'GET_DESCRIPTION_FOR_CONTEST_SUCCESS',
  GET_DESCRIPTION_FOR_CONTEST_FAILED: 'GET_DESCRIPTION_FOR_CONTEST_FAILED',

  GET_CONTEST_BY_ID: 'GET_CONTEST_BY_ID',
  GET_CONTEST_BY_ID_REQUEST: 'GET_CONTEST_BY_ID_REQUEST',
  GET_CONTEST_BY_ID_SUCCESS: 'GET_CONTEST_BY_ID_SUCCESS',
  GET_CONTEST_BY_ID_FAILED: 'GET_CONTEST_BY_ID_FAILED',

  UPDATE_CONTEST: 'UPDATE_CONTEST',
  UPDATE_CONTEST_REQUEST: 'UPDATE_CONTEST_REQUEST',
  UPDATE_CONTEST_SUCCESS: 'UPDATE_CONTEST_SUCCESS',
  UPDATE_CONTEST_FAILED: 'UPDATE_CONTEST_FAILED',

};

export default SINGLE_CONTEST_ACTION_TYPES;