const USER_ACTION_TYPES = {
  USER_UPDATE: 'USER_UPDATE',
  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_UPDATE_BALANCE: 'USER_UPDATE_BALANCE',
};

export default USER_ACTION_TYPES;